### ISSUE TITLE
Determine development stack/methodology

### ISSUE THREAD

**Issue by DLavin23** [cpww/beer_me#4]
Initially, we decided to create the app hosted on Heroku, using flask (to manage  the backend/API) and AngularJS (to manage the client/UI).   However, with the introduction of meteor, this setup is still open for debate. I'm fairly impartial so long as we go down a route that is, conducive to learning and widely used/supported (i.e. large community, tutorials, etc.). The goal is to learn shit that will help us become better, more valuable developers...at least that's my interpretation.

**Comment by Shiggiddie** [comment]
Meteor imo. Me I'm important is a set of tasks we cam begin tackling. One person could easily handle the meteor port in an hour or less. What will the others work on?

**Comment by DLavin23** [comment]
Relax bruh, I'll add some plenty of tasks. I had a few minutes over lunch and wanted to get something up here. 

—

**Comment by DLavin23** [comment]
Looks like we could get the best of both worlds...
- [Meteor and Angular together](https://medium.com/@zfxuan/the-wonderful-duo-using-meteor-and-angularjs-together-4d603a4651bf)
- https://github.com/Urigo/angular-meteor
- https://github.com/mondora/asteroid
